# Generated by Django 5.2.16 on 2026-07-28 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Comissão (%)'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff/photos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='specialties',
            field=models.CharField(blank=True, max_length=255, verbose_name='Especialidades'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='end_date',
            field=models.DateField(verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='staff.professional', verbose_name='Profissional'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='start_date',
            field=models.DateField(verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='break_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Fim do intervalo'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='break_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Início do intervalo'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='end_time',
            field=models.TimeField(verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='staff.professional', verbose_name='Profissional'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='start_time',
            field=models.TimeField(verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da semana'),
        ),
    ]
