# Generated by Django 5.2.16 on 2026-07-28 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('staff', '0001_initial'),
        ('tenants', '0002_seed_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='allowed_professionals',
            field=models.ManyToManyField(blank=True, related_name='services', to='staff.professional'),
        ),
        migrations.AddField(
            model_name='service',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicecategory'),
        ),
    ]
