# Generated by Django 5.2.16 on 2026-07-28 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
        ('staff', '0002_alter_professional_commission_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='allowed_professionals',
            field=models.ManyToManyField(blank=True, related_name='services', to='staff.professional', verbose_name='Profissionais habilitados'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicecategory', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='service',
            name='color',
            field=models.CharField(default='#2563eb', max_length=7, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(verbose_name='Duração (minutos)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
