# Generated by Django 5.2.16 on 2026-07-28 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_birth_date_alter_client_email_and_more'),
        ('scheduling', '0001_initial'),
        ('services', '0003_alter_service_allowed_professionals_and_more'),
        ('staff', '0002_alter_professional_commission_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motivo do cancelamento'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clients.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_at',
            field=models.DateTimeField(verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='origin',
            field=models.CharField(choices=[('syncora', 'Syncora'), ('google', 'Google Calendar'), ('outlook', 'Outlook'), ('apple', 'Apple Calendar')], default='syncora', max_length=20, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='staff.professional', verbose_name='Profissional'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='scheduling.room', verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='services.service', verbose_name='Serviço'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_at',
            field=models.DateTimeField(verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendado'), ('confirmed', 'Confirmado'), ('checked_in', 'Check-in'), ('completed', 'Concluído'), ('cancelled', 'Cancelado'), ('no_show', 'Não compareceu')], default='scheduled', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='block',
            name='end_at',
            field=models.DateTimeField(verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='block',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='staff.professional', verbose_name='Profissional'),
        ),
        migrations.AlterField(
            model_name='block',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='scheduling.room', verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='block',
            name='start_at',
            field=models.DateTimeField(verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='block',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.CharField(choices=[('almoco', 'Almoço'), ('ferias', 'Férias'), ('folga', 'Folga'), ('evento', 'Evento interno'), ('reuniao', 'Reunião'), ('data_comemorativa', 'Data comemorativa')], max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='room',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='scheduling.unit', verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='clients.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='desired_date',
            field=models.DateField(verbose_name='Data desejada'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='priority',
            field=models.PositiveIntegerField(default=0, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='staff.professional', verbose_name='Profissional'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='services.service', verbose_name='Serviço'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='status',
            field=models.CharField(choices=[('waiting', 'Aguardando'), ('fulfilled', 'Atendido'), ('cancelled', 'Cancelado')], default='waiting', max_length=20, verbose_name='Status'),
        ),
    ]
