# Generated by Django 5.2.16 on 2026-07-28 18:06

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        ('staff', '0001_initial'),
        ('tenants', '0002_seed_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('provider', models.CharField(choices=[('google', 'Google Calendar'), ('outlook', 'Outlook Calendar'), ('apple', 'Apple Calendar (iCloud)')], max_length=20)),
                ('access_token', apps.core.fields.EncryptedTextField(blank=True)),
                ('refresh_token', apps.core.fields.EncryptedTextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('external_calendar_id', models.CharField(blank=True, max_length=255)),
                ('sync_direction', models.CharField(choices=[('bidirectional', 'Bidirecional'), ('out_only', 'Somente Syncora → Calendário'), ('in_only', 'Somente Calendário → Syncora'), ('disabled', 'Desativada')], default='bidirectional', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_connections', to='staff.professional')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalEventMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('external_event_id', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_mappings', to='scheduling.appointment')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_mappings', to='calendar_sync.calendarconnection')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='calendarconnection',
            constraint=models.UniqueConstraint(fields=('professional', 'provider'), name='unique_connection_per_provider'),
        ),
        migrations.AddConstraint(
            model_name='externaleventmapping',
            constraint=models.UniqueConstraint(fields=('connection', 'external_event_id'), name='unique_external_event_per_connection'),
        ),
    ]
