# Generated by Django 5.2.16 on 2026-07-28 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='clients/photos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='document_type',
            field=models.CharField(choices=[('rg', 'RG'), ('cpf', 'CPF'), ('exam', 'Exame'), ('contract', 'Contrato'), ('other', 'Outro')], default='other', max_length=20, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='file',
            field=models.FileField(upload_to='clients/documents/', verbose_name='Arquivo'),
        ),
    ]
