# Generated by Django 5.2.16 on 2026-07-28 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_seed_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/logos/')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='branding/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/favicons/')),
                ('color_primary', models.CharField(default='#111827', max_length=7)),
                ('color_secondary', models.CharField(default='#6b7280', max_length=7)),
                ('color_button', models.CharField(default='#111827', max_length=7)),
                ('color_link', models.CharField(default='#2563eb', max_length=7)),
                ('color_sidebar', models.CharField(default='#111827', max_length=7)),
                ('color_topbar', models.CharField(default='#ffffff', max_length=7)),
                ('color_card', models.CharField(default='#ffffff', max_length=7)),
                ('color_icons', models.CharField(default='#111827', max_length=7)),
                ('chart_colors', models.JSONField(blank=True, default=list)),
                ('theme_mode', models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro'), ('auto', 'Automático (segue o sistema)')], default='auto', max_length=10)),
                ('login_background', models.ImageField(blank=True, null=True, upload_to='branding/login/')),
                ('login_message', models.CharField(blank=True, max_length=255)),
                ('show_powered_by', models.BooleanField(default=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
