# Generated by Django 5.2.16 on 2026-07-28 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('scheduling', '0001_initial'),
        ('tenants', '0002_seed_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notification_type', models.CharField(choices=[('confirmation', 'Confirmação de agendamento'), ('cancellation', 'Cancelamento'), ('reschedule', 'Remarcação'), ('reminder', 'Lembrete'), ('birthday', 'Aniversário'), ('return_reminder', 'Aviso de retorno')], max_length=30)),
                ('channel', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('failed', 'Falhou'), ('skipped', 'Ignorado')], max_length=20)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='scheduling.appointment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='clients.client')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'notification_type', 'created_at'], name='notificatio_client__e9995c_idx')],
            },
        ),
    ]
